### PR TITLE
SVCPLAN-2762 - Puppetize primary KDC

### PR DESCRIPTION
**Pull request by lindsey-ncsa**
Tested this on ncsa-krb-0

### CODE REVIEW

**Review by andylytical — COMMENTED** [review]
Looks good to me. Reviewed together in a working session.

**Review by andylytical — APPROVED** [review]
forgot to approve.

**Review by tbouvetncsa — COMMENTED** [review]
looks good

**Review by tbouvetncsa — APPROVED** [review]
looks good

**Pull request merged**
